<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
    /*. box{
            border:2px solid red;
            width: 25;
            
        } */
        .parent{
            border: 1px solid black;
            background-color:  aqua;

        }
        .child{
            border: 1px solid black;
            background-color:  red;

        

        }

        
    </style>
</head>
<body>
    <!--<div class="box">
        Welcome to INDIA
    </Div>-->
    <div class=""parent">
    <div class="child">
        CHILD
    </div>
    
</body>
</html>